Rewrite TCP and HTTP tests

diff --git a/.github/workflows/docker-integration-tests.yml b/.github/workflows/docker-integration-tests.yml
--- a/.github/workflows/docker-integration-tests.yml
+++ b/.github/workflows/docker-integration-tests.yml
@@ -7,6 +7,13 @@ jobs:
   tests:
     name: Integration Tests
     runs-on: ubuntu-22.04
+    env:
+      PORT=3000
+      DELAY=2
+      LIMIT=60
+      CMDCOMP="cd deploy; docker compose -f docker-compose-build.yml --env-file custom.env"
+      CMDHTTP="nc -zv -w1"
+      CMDCURL="curl -s -o /dev/null -w %{http_code}"
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -15,44 +22,32 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Build image and start services with Docker Compose
-        run: |
-          cd deploy
-          docker compose -f docker-compose-build.yml --env-file custom.env up -d
+        run: $CMDCOMP up -d
 
-      - name: Wait for the app to be ready
+      - name: Wait for the service to be available at the TCP level
         run: |
-          echo "Waiting for the app to become available on port 3000..."
-          timeout=100
-          interval=5
-          end=$((SECONDS+timeout))
-          while [ $SECONDS -lt $end ]; do
-            if nc -zv -w1 localhost 3000 2>/dev/null; then
-              echo "App is available!"
-              exit 0
-            else
-              echo "App not available yet, retrying in $interval seconds..."
-              sleep $interval
+          echo "Testing port readiness for localhost:$PORT (TCP level)..."; elapsed=0
+          while ! $CMDHTTP localhost $PORT 2>/dev/null; do
+            sleep $DELAY ; elapsed=$((elapsed + DELAY)); echo "Port not ready yet..."
+            if [ $elapsed -ge $LIMIT ]; then
+              echo "::error::Timeout! Port $PORT on localhost is not ready."
+              $CMDCOMP logs; exit 1;
             fi
           done
-          echo "App did not become available within $timeout seconds."
-          docker compose logs
-          exit 1
+          echo "::notice::TCP check passed after $elapsed seconds."
 
-      - name: Validate return from spina endpoint
+      - name: Wait for the app to respond requests with HTTP 200
         run: |
-          curl -o /dev/null -w "%{http_code}" http://localhost:3000/
-          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/)
-          echo $response ; curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/ #debug
-          if [ "$response" -eq "200" ]; then
-            echo "Integration test passed: Received 200 OK from the app."
-          else
-            echo "Integration test failed: Expected 200 OK, got $response."
-            exit 1
-          fi
+          echo "Testing endpoint readiness for localhost:$PORT (HTTP level)..."; elapsed=0
+          while return=$($CMDCURL http://localhost:$PORT/) ; [ $return -ne 200 ]; do
+            sleep $DELAY ; elapsed=$((elapsed + DELAY)); echo "HTTP not ready yet..."
+            if [ $elapsed -ge $LIMIT ]; then
+              echo "::error::Timeout! HTTP on localhost:$PORT is not ready (return code: $return)"
+              $CMDCOMP logs; exit 1;
+            fi
+          done
+          echo "::notice::HTTP check passed after $elapsed seconds."
 
       - name: Tear down services
         if: always()
-        run: |
-          cd deploy
-          docker compose -f docker-compose-build.yml --env-file custom.env down --volumes
-
+        run: $CMDCOMP down --volumes
